globalCss: |
  @font-face {
    font-family: 'Host Grotesk';
    src: url('/wwwroot/fonts/HostGrotesk-Regular.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
  }

colors:
  content-strong: "#0E121B"
  content-sub: "#222530"
  content-soft: "#525866"
  content-disable: "#CACFD8"
  content-weak: "#F5F7FA"
  content-white: "#FFFFFF"
  button-text-white: "#FFFFFF"
  border-strong: "#181B25"
  border-sub: "#CACFD8"
  border-soft: "#E1E4EA"
  border-white: "#FFFFFF"
  primary-dark: "#552502"
  primary-base: "#FF6E06"
  primary-light: "#FFB682"
  primary-lighter: "#FFE2CD"
  secondary-dark: "#14464F"
  secondary-base: "#3DD3EE"
  secondary-light: "#9EE9F6"
  secondary-lighter: "#D8F6FC"
  error-dark: "#4E190F"
  error-base: "#E94A2E"
  error-light: "#F4A496"
  error-lighter: "#FBDBD5"
  future-dark: "#281355"
  future-base: "#7939FF"
  future-light: "#BC9CFF"
  future-lighter: "#E4D7FF"


styles:
  bg-strong: "background: #0E121B"
  bg-surface: "background: #222530"
  bg-sub: "background: #CACFD8"
  bg-soft: "background: #E1E4EA"
  bg-weak: "background: #F5F7FA"
  bg-white: "background: #FFFFFF"
  heading-01: |
    font-family: "Host Grotesk";
    font-size: 56px;
    font-style: normal;
    font-weight: 600;
    line-height: 64px;
  heading-02: |
    font-family: "Host Grotesk";
    font-size: 48px;
    font-style: normal;
    font-weight: 600;
    line-height: 56px;
  heading-03: |
    font-family: "Host Grotesk";
    font-size: 40px;
    font-style: normal;
    font-weight: 600;
    line-height: 48px;
  heading-04: |
    font-family: "Host Grotesk";
    font-size: 32px;
    font-style: normal;
    font-weight: 600;
    line-height: 40px;
  heading-05: |
    font-family: "Host Grotesk";
    font-size: 24px;
    font-style: normal;
    font-weight: 600;
    line-height: 32px;
  heading-06: |
    font-family: "Host Grotesk";
    font-size: 20px;
    font-style: normal;
    font-weight: 600;
    line-height: 28px;
  body-XL: |
    font-family: "Host Grotesk";
    font-size: 20px;
    font-style: normal;
    font-weight: 400;
    line-height: 32px;
  body-L: |
    font-family: "Host Grotesk";
    font-size: 18px;
    font-style: normal;
    font-weight: 400;
    line-height: 26px;
  body-M: |
    font-family: "Host Grotesk";
    font-size: 16px;
    font-style: normal;
    font-weight: 400;
    line-height: 24px;
  body-S: |
    font-family: "Host Grotesk";
    font-size: 14px;
    font-style: normal;
    font-weight: 400;
    line-height: 20px;
  body-XS: |
    font-family: "Host Grotesk";
    font-size: 12px;
    font-style: normal;
    font-weight: 400;
    line-height: 16px;
 
  label-XXL: |
    font-family: "Host Grotesk";
    font-size: 24px;
    font-style: normal;
    font-weight: 500;
    line-height: 32px;

  label-XL: |
    font-family: "Host Grotesk";
    font-size: 20px;
    font-style: normal;
    font-weight: 500;
    line-height: 28px;

  label-L: |
    font-family: "Host Grotesk";
    font-size: 18px;
    font-style: normal;
    font-weight: 500;
    line-height: 26px;

  label-M: |
    font-family: "Host Grotesk";
    font-size: 16px;
    font-style: normal;
    font-weight: 500;
    line-height: 24px;
  
  label-S: |
    font-family: "Host Grotesk";
    font-size: 14px;
    font-style: normal;
    font-weight: 500;
    line-height: 20px;

  label-XS: |
    font-family: "Host Grotesk";
    font-size: 12px;
    font-style: normal;
    font-weight: 500;
    line-height: 16px;


  # s u b t i t l e
  subTitle-XXL: |
    font-family: "Host Grotesk";
    font-size: 24px;
    font-style: normal;
    font-weight: 600;
    line-height: 32px;
  
  subTitle-XL: |
    font-family: "Host Grotesk";
    font-size: 20px;
    font-style: normal;
    font-weight: 600;
    line-height: 28px;
  
  subTitle-L: |
    font-family: "Host Grotesk";
    font-size: 18px;
    font-style: normal;
    font-weight: 600;
    line-height: 26px;
  
  subTitle-M: |
    font-family: "Host Grotesk";
    font-size: 16px;
    font-style: normal;
    font-weight: 600;
    line-height: 24px;
  
  subTitle-S: |
    font-family: "Host Grotesk";
    font-size: 14px;
    font-style: normal;
    font-weight: 600;
    line-height: 20px;
  
  subTitle-XS: |
    font-family: "Host Grotesk";
    font-size: 12px;
    font-style: normal;
    font-weight: 600;
    line-height: 16px;

  # tailwind like shorthands
  w-full: 'width: 100%;'
  w-fit: 'width: fit-content;'
  h-full: 'height: 100%;'
  h-fit: 'height: fit-content;'
  size-full: 'width: 100%; height: 100%;'
  size-fit: 'width: fit-content; height: fit-content;'
  row: 'display: flex'
  col: 'display: flex; flex-direction: column;'
  flex-row-centered: 'display: flex; justify-content: center; align-items: center;'
  flex-col-centered: 'display: flex; justify-content: center; align-items: center; flex-direction: column;'
  w-1/2: 'width: 50%;'
  w-1/3: 'width: 33.333333%;'
  w-2/3: 'width: 66.666667%;'
  w-1/4: 'width: 25%;'
  w-2/4: 'width: 50%;'
  w-3/4: 'width: 75%;'
  w-1/5: 'width: 20%;'
  w-2/5: 'width: 40%;'
  w-3/5: 'width: 60%;'
  w-4/5: 'width: 80%;'
  w-1/6: 'width: 16.666667%;'
  w-2/6: 'width: 33.333333%;'
  w-3/6: 'width: 50%;'
  w-4/6: 'width: 66.666667%;'
  w-5/6: 'width: 83.333333%;'
  w-1/12: 'width: 8.333333%;'
  w-2/12: 'width: 16.666667%;'
  w-3/12: 'width: 25%;'
  w-4/12: 'width: 33.333333%;'
  w-5/12: 'width: 41.666667%;'
  w-6/12: 'width: 50%;'
  w-7/12: 'width: 58.333333%;'
  w-8/12: 'width: 66.666667%;'
  w-9/12: 'width: 75%;'
  w-10/12: 'width: 83.333333%;'
  w-11/12: 'width: 91.666667%;'
  rounded-none: 'border-radius: 0px;'
  rounded-sm: 'border-radius: 2px;'
  rounded: 'border-radius: 4px;'
  rounded-md: 'border-radius: 6px;'
  rounded-lg: 'border-radius: 8px;'
  rounded-xl: 'border-radius: 12px;'
  rounded-2xl: 'border-radius: 16px;'
  rounded-3xl: 'border-radius: 24px;'
  rounded-full: 'border-radius: 9999px;'

  border: 'border-width: 1px; border-style: solid;'

  justify-between: 'justify-content: space-between;'
  items-center: 'align-items: center;'


suggestions:
  width: ['auto', 'fit-content', 'max-content', 'min-content', 'inherit', 'initial', 'unset', '100%', '75%', '50%', '25%']
  height: ['auto', 'fit-content', 'max-content', 'min-content', 'inherit', 'initial', 'unset', '100%', '75%', '50%', '25%']
  display: ['flex']
  position: ['static', 'relative', 'absolute', 'fixed', 'sticky', 'inherit', 'initial', 'unset']
  flex-direction: ['row', 'row-reverse', 'column', 'column-reverse', 'inherit', 'initial', 'unset']
  justify-content: ['flex-start', 'flex-end', 'center', 'space-between', 'space-around', 'space-evenly', 'inherit', 'initial', 'unset']
  align-items: ['stretch', 'flex-start', 'flex-end', 'center', 'baseline', 'inherit', 'initial', 'unset']
  overflow: ['visible', 'hidden', 'scroll', 'auto', 'clip', 'inherit', 'initial', 'unset']
  visibility:  ['visible', 'hidden', 'collapse', 'inherit', 'initial', 'unset']
  opacity:  ['0', '0.1', '0.5', '1', 'inherit', 'initial', 'unset']
  cursor: ['auto', 'default', 'pointer', 'wait', 'text', 'move', 'not-allowed', 'crosshair', 'inherit', 'initial', 'unset']
  font-size: ['small', 'medium', 'large', 'inherit', 'initial', 'unset', '16px', '1.2rem']
  font-weight: ['normal', 'bold', 'bolder', 'lighter', '100', '200', '300', 'inherit', 'initial', 'unset']
  line-height: ['normal', 'inherit', 'initial', 'unset', '1.5', '2']
  text-align: ['left', 'right', 'center', 'justify', 'inherit', 'initial', 'unset']
  text-decoration: ['none', 'underline', 'overline', 'line-through', 'inherit', 'initial', 'unset']
  white-space: ['normal', 'nowrap', 'pre', 'pre-wrap', 'pre-line', 'inherit', 'initial', 'unset']
  pointer-events: ['auto', 'none', 'inherit', 'initial', 'unset']